Repository WalletWasabi/WasabiDoc, pull requests merged in 2019-08, with the labels that each got.

#50 vuepress automatic table of content
  docs/FAQ/FAQ-Installation.md
  docs/FAQ/FAQ-UseWasabi.md
  docs/building-wasabi/CodingConventions.md
  docs/building-wasabi/ContributionChecklist.md
  docs/building-wasabi/DemoGuide.md
  docs/building-wasabi/HowToDebug.md
  docs/building-wasabi/ManualTesting.md
  docs/building-wasabi/TechnicalOverview.md
  docs/using-wasabi/BIP.md
  docs/using-wasabi/BackendDeployment.md
  docs/using-wasabi/ClientDeployment.md
  docs/using-wasabi/DeterministicBuild.md
  docs/using-wasabi/InstallPackage.md
  docs/using-wasabi/NetworkLevelPrivacy.md
  docs/using-wasabi/PasswordFinder.md
  docs/using-wasabi/PayToEndPoint.md
  docs/why-wasabi/10Commandments.md
  docs/why-wasabi/BitcoinPrivacy.md
Labels: question, structure, visual

#51 Address Reuse
  docs/.vuepress/config.js
  docs/using-wasabi/AddressReuse.md
Labels: Using wasabi

#52 Improvements
  docs/.vuepress/config.js
  package-lock.json
  package.json
Labels: ready for review, visual

#55 New Writing Convention: Each sentence new line
  README.md
  docs/FAQ/FAQ-Installation.md
  docs/FAQ/FAQ-Introduction.md
  docs/FAQ/FAQ-UseWasabi.md
  docs/FAQ/README.md
  docs/IntroWasabi.md
  docs/README.md
  docs/building-wasabi/CodeCoverage.md
  docs/building-wasabi/CodingConventions.md
  docs/building-wasabi/ContributionChecklist.md
  docs/building-wasabi/ContributionGame.md
  docs/building-wasabi/DemoGuide.md
  docs/building-wasabi/Dojo.md
  docs/building-wasabi/HardwareWalletTestingGuide.md
  docs/building-wasabi/HowToDebug.md
  docs/building-wasabi/ManualTesting.md
  docs/building-wasabi/Security.md
  docs/building-wasabi/TechnicalOverview.md
  docs/building-wasabi/ToDo.md
  docs/using-wasabi/BIP.md
  docs/using-wasabi/BackendDeployment.md
  docs/using-wasabi/DeterministicBuild.md
  docs/using-wasabi/InstallPackage.md
  docs/using-wasabi/NetworkLevelPrivacy.md
  docs/using-wasabi/PasswordFinder.md
  docs/using-wasabi/PayToEndPoint.md
  docs/why-wasabi/10Commandments.md
  docs/why-wasabi/BitcoinPrivacy.md
  docs/why-wasabi/WhyPrivacyImportant.md
Labels: ready for review, structure

#56 New Images
  docs/.vuepress/public/CoinJoinAnonsetTarget.png
  docs/.vuepress/public/CoinJoinStatus.png
  docs/.vuepress/public/DownloadAll.png
  docs/.vuepress/public/DownloadDeb.png
  docs/.vuepress/public/DownloadLinux.png
  docs/.vuepress/public/DownloadMac.png
  docs/.vuepress/public/DownloadTar.png
  docs/.vuepress/public/DownloadWindows.png
  docs/.vuepress/public/GenerateWallet.png
  docs/.vuepress/public/MenuFile.png
  docs/.vuepress/public/MenuHelp.png
  docs/.vuepress/public/MenuTools.png
  docs/.vuepress/public/Receive.png
  docs/.vuepress/public/ReceiveAddressDropDown.png
  docs/.vuepress/public/ReceiveAddressMenu.png
  docs/.vuepress/public/ReceiveLabelingRequired.png
  docs/.vuepress/public/RecoveryWords.png
  docs/.vuepress/public/SendAmountFeePassword.png
  docs/.vuepress/public/SendFeeSlider.png
  docs/.vuepress/public/SendNoFee.png
  docs/.vuepress/public/SendPrivacyShields.png
  docs/.vuepress/public/SettingsAnonLevels.png
  docs/.vuepress/public/SettingsDustThreshold.png
  docs/.vuepress/public/SettingsNetwork.png
  docs/.vuepress/public/StatusBar.png
  docs/.vuepress/public/StatusBarBackendConnected.png
  docs/.vuepress/public/StatusBarDownloadBlock.png
  docs/.vuepress/public/StatusBarMempool.png
  docs/.vuepress/public/StatusBarPeers.png
  docs/.vuepress/public/StatusBarPrice.png
  docs/.vuepress/public/StatusBarReady.png
  docs/.vuepress/public/StatusBarTorRunning.png
  docs/.vuepress/public/TestPassword.png
  docs/.vuepress/public/WalletExplorer.png
  docs/.vuepress/public/WalletInfoHidden.png
  docs/.vuepress/public/WalletInfoRevealed.png
  docs/.vuepress/public/WalletManagerLoadWallet.png
  docs/building-wasabi/TechnicalOverview.md
  docs/using-wasabi/InstallPackage.md
Labels: structure, visual

#10 Explain Zero Link Phases
  docs/FAQ/FAQ-UseWasabi.md
Labels: FAQ, help wanted, question, ready for review

#53 Adapt theme from new website design
  docs/.vuepress/config.js
  docs/.vuepress/styles/index.styl
  docs/.vuepress/styles/palette.styl
Labels: ready for review, visual

#68 Infographic to /Why-Wasabi/README
  docs/.vuepress/config.js
  docs/.vuepress/public/InfographicWhyWasabi.png
  docs/why-wasabi/README.md
Labels: visual, why wasabi

#78 add several embeded videos
  docs/FAQ/FAQ-Contribution.md
  docs/FAQ/FAQ-Installation.md
  docs/FAQ/FAQ-UseWasabi.md
  docs/using-wasabi/NetworkLevelPrivacy.md
  docs/why-wasabi/WhyPrivacyImportant.md
Labels: visual

#77 Update FAQ-GeneralBitcoinPrivacy.md
  docs/FAQ/FAQ-GeneralBitcoinPrivacy.md
Labels: FAQ

#86 [FIX] You to you
  docs/FAQ/FAQ-Contribution.md
  docs/FAQ/FAQ-Installation.md
  docs/FAQ/FAQ-Introduction.md
  docs/FAQ/FAQ-UseWasabi.md
  docs/building-wasabi/DemoGuide.md
Labels: typo

#89 Edit the main README file
  README.md
Labels: typo

#131 [FIX] remove backend and client deployment
  docs/.vuepress/config.js
  docs/using-wasabi/BackendDeployment.md
  docs/using-wasabi/ClientDeployment.md
Labels: duplicate, structure

#79 Add details toggles for FAQs
  docs/.vuepress/config.js
  docs/.vuepress/enhanceApp.js
  docs/.vuepress/styles/index.styl
  docs/FAQ/FAQ-Contribution.md
  docs/FAQ/FAQ-GeneralBitcoinPrivacy.md
  docs/FAQ/FAQ-Installation.md
  docs/FAQ/FAQ-Introduction.md
  docs/FAQ/FAQ-UseWasabi.md
  package.json
Labels: FAQ, ready for review, structure, visual

#132 [STRUCTUR] Add issue templates
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/question.md
Labels: ready for review, structure

#139 [STRUCTURE] Add Description to each file
  docs/.vuepress/config.js
  docs/FAQ/FAQ-Contribution.md
  docs/FAQ/FAQ-GeneralBitcoinPrivacy.md
  docs/FAQ/FAQ-Installation.md
  docs/FAQ/FAQ-Introduction.md
  docs/FAQ/FAQ-UseWasabi.md
  docs/building-wasabi/CodeCoverage.md
  docs/building-wasabi/CodingConventions.md
  docs/building-wasabi/ContributionChecklist.md
  docs/building-wasabi/ContributionGame.md
  docs/building-wasabi/DemoGuide.md
  docs/building-wasabi/Dojo.md
  docs/building-wasabi/HardwareWalletTestingGuide.md
  docs/building-wasabi/HowToDebug.md
  docs/building-wasabi/LICENSE.md
  docs/building-wasabi/ManualTesting.md
  docs/building-wasabi/Ports.md
  docs/building-wasabi/Security.md
  docs/building-wasabi/TechnicalOverview.md
  docs/building-wasabi/ToDo.md
  docs/using-wasabi/.LostPassword.md.swp
  docs/using-wasabi/AddressReuse.md
  docs/using-wasabi/BIP.md
  docs/using-wasabi/BuildSource.md
  docs/using-wasabi/Daemon.md
  docs/using-wasabi/DeterministicBuild.md
  docs/using-wasabi/InstallPackage.md
  docs/using-wasabi/LostPassword.md
  docs/using-wasabi/NetworkLevelPrivacy.md
  docs/using-wasabi/PasswordFinder.md
  docs/using-wasabi/PayToEndPoint.md
  docs/why-wasabi/10Commandments.md
  docs/why-wasabi/BitcoinPrivacy.md
  docs/why-wasabi/WhyPrivacyImportant.md
Labels: ready for review, structure

#144 Fix typos
  docs/using-wasabi/WalletGeneration.md
Labels: typo

#149 [STRUCTURE] using sidebar submenu
  docs/.vuepress/config.js
Labels: Using wasabi, structure, visual

#141 Update FAQ-Introduction.md
  docs/FAQ/FAQ-Introduction.md
Labels: FAQ

#152 Videos: Add preview, play on click
  README.md
  docs/.vuepress/config.js
  docs/.vuepress/enhanceApp.js
  docs/.vuepress/styles/index.styl
  docs/FAQ/FAQ-Installation.md
Labels: ready for review, visual

#153 Add OSX video guide
  docs/using-wasabi/InstallPackage.md
Labels: Using wasabi, ready for review

#156 Update FAQ-Introduction.md
  docs/FAQ/FAQ-Introduction.md
Labels: FAQ

#161 [STRUCTURE] make BIPs dropdown
  docs/using-wasabi/BIP.md
Labels: Using wasabi, ready for review, structure
