Repository WalletWasabi/WasabiDoc, pull requests merged in 2019-07, with the labels that each got.

#18 Add Basics of Bitcoin Privacy
  docs/BitcoinPrivacy.md
  docs/README.md
Labels: main docs, ready for review

#19 Import 10 commandments
  docs/10Commandments.md
  docs/README.md
Labels: main docs

#20 Import Bitcoin Core vs Wasabi - Network Level Privacy
  docs/NetworkLevelPrivacy.md
  docs/README.md
Labels: main docs

#24 Add ToDo list for short and long term
  docs/ContributionChecklist.md
  docs/README.md
  docs/ToDo.md
Labels: main docs

#26 Build docs with Vuepress
  .gitignore
  .travis.yml
  CNAME
  README.md
  deploy.sh
  docs/.gitbook.yaml
  docs/.vuepress/config.js
  docs/.vuepress/public/Logo_with_text.png
  docs/.vuepress/public/Logo_without_text.png
  docs/FAQ/README.md
  docs/GettingStarted.md
  docs/README.md
  docs/SUMMARY.md
  package-lock.json
  package.json
Labels: ready for review, visual

#32 Three Pillar Structure
  docs/.vuepress/config.toml
  docs/README.md
  docs/building-wasabi/CodeCoverage.md
  docs/building-wasabi/CodingConventions.md
  docs/building-wasabi/ContributionChecklist.md
  docs/building-wasabi/ContributionGame.md
  docs/building-wasabi/DemoGuide.md
  docs/building-wasabi/Dojo.md
  docs/building-wasabi/HardwareWalletTestingGuide.md
  docs/building-wasabi/HowToDebug.md
  docs/building-wasabi/ManualTesting.md
  docs/building-wasabi/Ports.md
  docs/building-wasabi/README.md
  docs/building-wasabi/Security.md
  docs/building-wasabi/TechnicalOverview.md
  docs/building-wasabi/ToDo.md
  docs/using-wasabi/BackendDeployment.md
  docs/using-wasabi/BuildSource.md
  docs/using-wasabi/ClientDeployment.md
  docs/using-wasabi/DeterministicBuild.md
  docs/using-wasabi/InstallPackage.md
  docs/using-wasabi/NetworkLevelPrivacy.md
  docs/using-wasabi/PasswordFinder.md
  docs/using-wasabi/PayToEndPoint.md
  docs/using-wasabi/README.md
  docs/why-wasabi/README.md
Labels: ready for review

#22 List and Describe the supported BIPs
  docs/using-wasabi/BIP.md
Labels: help wanted

#43 Import Images to New Structure
  docs/.vuepress/public/CoinJoin.png
  docs/.vuepress/public/CoinJoinCoinsBeingCoinJoined.png
  docs/.vuepress/public/ContributionGame.png
  docs/.vuepress/public/Dojo.png
  docs/.vuepress/public/DownloadLinux.png
  docs/.vuepress/public/DownloadMac.png
  docs/.vuepress/public/DownloadWindows.png
  docs/.vuepress/public/History.png
  docs/.vuepress/public/InstallMacConfirmOpen.png
  docs/.vuepress/public/InstallMacDragDrop.png
  docs/.vuepress/public/InstallWindowsGUIVerify.png
  docs/.vuepress/public/InstallWindowsGpgp4winSetup.png
  docs/.vuepress/public/InstallWindowsImportPGPManualImport.png
  docs/.vuepress/public/InstallWindowsImportPGPManualKleopatra.png
  docs/.vuepress/public/InstallWindowsImportPGPManualNewFile.png
  docs/.vuepress/public/InstallWindowsImportPGPManualText.png
  docs/.vuepress/public/InstallWindowsKleopatraImportPGP.png
  docs/.vuepress/public/InstallWindowsKleopatraPGPConfirm.png
  docs/.vuepress/public/InstallWindowsKleopatraSearchPGP.png
  docs/.vuepress/public/InstallWindowsKleopatraValidSig.png
  docs/.vuepress/public/InstallWindowsKleopatraVerifyFingerprint.png
  docs/.vuepress/public/PGPRawText.png
  docs/.vuepress/public/Receive.png
  docs/.vuepress/public/ReceiveLabelingRequired.png
  docs/.vuepress/public/Send.png
  docs/.vuepress/public/SendAmountFeePassword.png
  docs/.vuepress/public/SendAnonset.png
  docs/.vuepress/public/StatusBarBackendConnected.png
  docs/.vuepress/public/StatusBarMempool.png
  docs/.vuepress/public/StatusBarPeers.png
  docs/.vuepress/public/StatusBarTorRunning.png
  docs/.vuepress/public/TXCoinJoin.png
  docs/.vuepress/public/WalletManagerLoadWallet.png
  docs/building-wasabi/ContributionGame.md
  docs/building-wasabi/Dojo.md
  docs/building-wasabi/TechnicalOverview.md
  docs/using-wasabi/InstallPackage.md
Labels: help wanted, structure, visual

#36 More on how to build website locally
  README.md
Labels: ready for review, structure
